SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[SP_UPD_USUARIO]
   @PI_ID_USUARIO integer,
   @PV_CODIGO VARCHAR (20),
   @PV_NOMBRES VARCHAR (100),
   @PV_APELLIDOS VARCHAR (100),
   @PV_MAIL VARCHAR (100),
   @PD_FECHA_NACIMIENTO DATETIME,
   @PV_CONTRASENA VARCHAR (100),
   @PI_USUARIO_MODICFICACION INTEGER


AS
	
BEGIN
   UPDATE USUARIOS
   SET CODIGO=@PV_CODIGO,
   NOMBRES=@PV_NOMBRES,
   APELLIDOS=@PV_APELLIDOS,
   MAIL=@PV_MAIL,
   FECHA_NACIMIENTO=@PD_FECHA_NACIMIENTO,
   CONTRASENA=@PV_CONTRASENA,
   USUARIO_MODIFICACION=@PI_USUARIO_MODICFICACION,
   FECHA_MODIFICACION=GETDATE() 
WHERE
  ID_USUARIO=@PI_ID_USUARIO


END